### ISSUE TITLE
[Nether Extension] Suave tipped arrows unlocalized 

### ISSUE THREAD

**Issue by TrueGkoliver** [team-abnormals/indev-issues#1]
Suave tipped arrows, although craftable, do not have localization. Other similar base potion arrows are simply called "Tipped Arrow". An image of this is attached.

[Link](https://cdn.discordapp.com/attachments/766002838198681623/827616688127868979/suave.PNG)

This is using the version of Nether Extension bundled with the pack, which I believe is this most recent one.

**Comment by bageldotjpg** [comment]
Fixed indev 👍
