### ISSUE TITLE
[Caverns and Chasms] Glare crash when loading world

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/indev-issues#31]
I summoned a rat, quit the world, and when I started reopening it, it crashed every single time :(
Crash report: https://gist.github.com/thelegitdolt/5bc78c8a62f639fae43d4e6fa6911451
Latest.log: https://gist.github.com/thelegitdolt/ed56988311507faa28ba15c5e57b6a9f

**Comment by LaGz4643** [comment]
From the crash report it looks like a Glare is causing the crash.

**Comment by LaGz4643** [comment]
I just got this same crash for the first time and it happened when I rejoined a world while a Glare was following me.

**Comment by laserlemons** [comment]
Anyone know if it's possible to get the world to load after this crash? I'm not having any luck.

Edit: Install "Bad Mobs" and set Glare to "removeAggressively = true" in the config to fix it.
