### ISSUE TITLE
[Caverns and Chasms] Clock, Compass, and Depth Gauge show tooltip information when in Dimensions other than the Overworld

### ISSUE THREAD

**Issue by LaGz4643** [team-abnormals/indev-issues#42]
Even though these items do not visually show information when in other dimensions, they still show information in the item's tooltip. The Barometer does not have this issue.

**Comment by bageldotjpg** [comment]
This is intentional, because they are meant to show the actual data as an alternative to the F3 menu - which should be available in these dimensions. The Nether still has coordinates and time, the visuals just bug out. The Barometer works properly because the Nether does not have weather.
