### ISSUE TITLE
Puff Bug Bottles crash game when fed to booflos

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [team-abnormals/indev-issues#5]
[
[crash-2021-05-07_11.57.51-client.txt](https://github.com/team-abnormals/indev-issues/files/6438926/crash-2021-05-07_11.57.51-client.txt)
](url)
When feeding bottles to booflos, the game crashes after a while

Mod: Endergetic
Version: Latest Dev build

**Comment by SmellyModder** [comment]
Fixed in https://github.com/team-abnormals/endergetic/commit/fe0df0e5943ca9a373b35ef018df60e5ebc29636
