### ISSUE TITLE
[Caverns and Chasms] [Suggestion] Changes to Deeper spawning

### ISSUE THREAD

**Issue by LaGz4643** [team-abnormals/indev-issues#63]
Currently, there is a tag that decides which blocks Deepers can spawn on which contains Ores, Stone variants, and Gravel. This means that any spawns on blocks such as Dripstone Blocks, and inside of underground structures such as Dungeons, Strongholds and on Planks in Mineshafts, will be Creepers instead of Deepers. It also means that spawns on any underground blocks/structures added by other mods would be Creepers as well by default, unless changed with a datapack. Instead, it might work to allow Deepers to spawn on any block, and to have a blacklist tag for blocks that Deepers should not spawn on. By default, this tag could include Moss Blocks, Clay, Azaleas, and Flowering Azaleas to keep the current behavior of allowing normal Creepers to spawn in Lush Caves. It could also include the #minecraft:sand tag and the #minecraft:dirt tag, which also contains Grass Blocks, Podzol, and Mycelium, to prevent Deepers from spawning in places where the surface rarely drops below y 60. I might be missing something that would make this not work as well as the current Deeper spawning.

**Comment by bageldotjpg** [comment]
This is actually intentional - since Creepers do less damage than Deepers we prefer they spawn in structures so they do less damage to the structure
