### ISSUE TITLE
Shulker Bullet Ticking Crash - Suspect Caverns and Chasms

### ISSUE THREAD

**Issue by annastropha** [team-abnormals/indev-issues#80]
Found when exploring an end city, fighting Shulkers.  Unsure what happened - Allurement and Quark are mixed in close to the crash point, but don't have code touching that method - seems likely to be Caverns and Chasms related.

[Crash log](https://pastebin.com/Bnhy7dqj)

[Likely related crash filed on Allurement](https://github.com/team-abnormals/allurement/issues/41)

**Comment by GitJhopa** [comment]
Too problem..
